### ISSUE TITLE
有点小问题

### ISSUE THREAD

**Issue by zxc-98** [HelloWorld-Ian/Huawei_CodeCraft_2021#1]
请问同学，发生了这个异常是怎么回事呀？

java.lang.ArrayIndexOutOfBoundsException: 1
	at com.huawei.java.main.In.PrepareData(In.java:59)
	at com.huawei.java.main.Main.main(Main.java:10)
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at com.huawei.java.main.Main.main(Main.java:22)

**Comment by zxc-98** [comment]
方便的话，可以加一下QQ请教一下吗？
这是我的QQ：1036795393

**Comment by HelloWorld-Ian** [comment]
注意数据集的格式哦，程序录入数据集数据时报错了


| |
aa15340521294
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年5月1日 ***@***.***> 写道：

请问同学，发生了这个异常是怎么回事呀？

java.lang.ArrayIndexOutOfBoundsException: 1
at com.huawei.java.main.In.PrepareData(In.java:59)
at com.huawei.java.main.Main.main(Main.java:10)
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:659)
at java.util.ArrayList.get(ArrayList.java:435)
at com.huawei.java.main.Main.main(Main.java:22)
